"""Render the physics-ablation results as paper-ready tables and bars.

Reads `physics_ablations.json` produced by `physics_ablations.py`, and
writes:
    fig_physics_ablations_bars.{pdf,png}  — RMSE Δ bars grouped by family
    table_physics_ablations.tex           — formatted LaTeX table
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import matplotlib.pyplot as plt
import numpy as np

from cranpm_plots import apply_paper_style, save_figure

FAMILY_COLORS = {
    "control": "#7f7f7f",
    "elevation": "#8c564b",
    "wind": "#1f77b4",
    "chemistry": "#2ca02c",
    "temporal": "#d62728",
    "geometry": "#9467bd",
}


def render_bars(results, output_dir: Path):
    apply_paper_style()
    rows = [r for r in results if r["slug"] != "baseline"]
    rows.sort(key=lambda r: r["rmse_delta"], reverse=True)

    labels = [r["description"] for r in rows]
    deltas = [r["rmse_delta"] for r in rows]
    colors = [FAMILY_COLORS.get(r["family"], "#888") for r in rows]

    fig, ax = plt.subplots(figsize=(11, max(4.0, 0.3 * len(rows))))
    y = np.arange(len(rows))
    bars = ax.barh(y, deltas, color=colors, edgecolor="white", linewidth=0.4)
    ax.set_yticks(y)
    ax.set_yticklabels(labels, fontsize=8)
    ax.invert_yaxis()
    ax.axvline(0, color="#444", linewidth=0.6)
    ax.set_xlabel("RMSE Δ vs baseline (µg m$^{-3}$, larger = bigger physics effect)")
    ax.grid(axis="x", linestyle="--", alpha=0.4)
    ax.set_axisbelow(True)

    for b, v in zip(bars, deltas):
        ax.text(v + 0.05 * (1 if v >= 0 else -1),
                b.get_y() + b.get_height() / 2,
                f"{v:+.2f}", va="center",
                ha="left" if v >= 0 else "right", fontsize=7)

    handles = [plt.Rectangle((0, 0), 1, 1, facecolor=c, edgecolor="white")
               for c in FAMILY_COLORS.values()]
    ax.legend(handles, list(FAMILY_COLORS.keys()),
              loc="lower right", fontsize=7, ncol=2,
              frameon=True, facecolor="white", edgecolor="#bbb")

    fig.suptitle("Physics ablation: RMSE degradation when each prior is corrupted",
                 y=0.995)
    fig.tight_layout(rect=[0, 0, 1, 0.97])
    save_figure(fig, "fig_physics_ablations_bars")
    plt.close(fig)


def render_latex_table(results, output_dir: Path):
    out = output_dir / "table_physics_ablations.tex"
    with open(out, "w") as fh:
        fh.write("% Auto-generated by fig_physics_ablations_table.py\n")
        fh.write("\\begin{tabular}{l l r r r r}\n")
        fh.write("\\toprule\n")
        fh.write("Family & Intervention & RMSE & RMSE $\\Delta$ & R$^2$ & R$^2$ $\\Delta$ \\\\\n")
        fh.write("\\midrule\n")
        for r in results:
            fh.write(
                f"{r['family']} & {r['description']} & "
                f"{r['rmse']:.2f} & {r['rmse_delta']:+.2f} & "
                f"{r['r2']:.3f} & {r['r2_delta']:+.3f} \\\\\n"
            )
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
    print(f"Wrote {out}")


def render_multi_model_heatmap(all_results: dict, output_dir: Path):
    """Heatmap: model rows × ablation columns, colour = RMSE Δ vs that model's baseline.

    Reading the figure: a model that *uses the physics* shows large positive
    deltas under randomization. A model that *ignores* a feature shows ~0
    delta — its predictions are unchanged when the feature is corrupted.
    """
    apply_paper_style()
    if not all_results:
        return
    # Use the union of ablation slugs (excluding baseline) in display order.
    ref_slugs = [r["slug"] for r in next(iter(all_results.values()))
                 if r["slug"] != "baseline"]
    ref_labels = {r["slug"]: r["description"]
                  for r in next(iter(all_results.values()))}

    model_order = [m for m in
                   ["cranpm", "topoflow", "climax", "earthformer", "simvp", "convlstm"]
                   if m in all_results]
    matrix = np.full((len(model_order), len(ref_slugs)), np.nan)
    for mi, m in enumerate(model_order):
        slug_to_delta = {r["slug"]: r["rmse_delta"] for r in all_results[m]}
        for si, slug in enumerate(ref_slugs):
            if slug in slug_to_delta:
                matrix[mi, si] = slug_to_delta[slug]

    fig, ax = plt.subplots(figsize=(13, 0.5 * len(model_order) + 1.6))
    vmax = np.nanmax(np.abs(matrix)) if np.any(np.isfinite(matrix)) else 1.0
    im = ax.imshow(matrix, cmap="RdBu_r", aspect="auto",
                   vmin=-vmax, vmax=vmax)
    ax.set_yticks(np.arange(len(model_order)))
    ax.set_yticklabels([m.upper() for m in model_order])
    ax.set_xticks(np.arange(len(ref_slugs)))
    ax.set_xticklabels([ref_labels[s] for s in ref_slugs],
                       rotation=30, ha="right", fontsize=7)
    for mi in range(matrix.shape[0]):
        for si in range(matrix.shape[1]):
            v = matrix[mi, si]
            if np.isfinite(v):
                color = "white" if abs(v) > vmax * 0.55 else "#222"
                ax.text(si, mi, f"{v:+.2f}",
                        ha="center", va="center", color=color, fontsize=7)
    cbar = fig.colorbar(im, ax=ax, shrink=0.85, pad=0.02)
    cbar.set_label("RMSE Δ vs each model's baseline (µg m$^{-3}$)")
    ax.set_title("Physics ablation across forecasting methods "
                 "(positive Δ = model uses the corrupted prior)")
    fig.tight_layout()
    save_figure(fig, "fig_physics_ablations_heatmap")
    plt.close(fig)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, required=True,
                        help="Either a single-model json or the combined "
                             "physics_ablations_all.json.")
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args(argv)

    with open(args.results) as fh:
        loaded = json.load(fh)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    if isinstance(loaded, list):
        # Single-model format.
        render_bars(loaded, args.output_dir)
        render_latex_table(loaded, args.output_dir)
    elif isinstance(loaded, dict):
        # Multi-model: render bars for each + a joint heatmap.
        for model, rows in loaded.items():
            if model == "cams_reference":
                continue
            render_bars(rows, args.output_dir / f"by_model_{model}")
        render_multi_model_heatmap(loaded, args.output_dir)
        # Render the LaTeX table for CRAN-PM (the main subject).
        if "cranpm" in loaded:
            render_latex_table(loaded["cranpm"], args.output_dir)


if __name__ == "__main__":
    sys.exit(main())
